[workspace]
members = ["algo", "node-binding", "python-binding"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
algo = { path = "./algo" }


[profile.release]
lto = true
